# Generated by Django 4.2.29 on 2026-04-21 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0004_alter_facility_options_facility_is_active"),
        ("shared", "0002_address_country_alter_address_city_and_more"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="patient",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="patient",
            name="sex_at_birth",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("intersex", "Intersex"),
                    ("unknown", "Unknown"),
                    ("undisclosed", "Undisclosed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="ssn_last4",
            field=models.CharField(
                blank=True,
                help_text="Store only the last 4 digits until encrypted full-SSN storage is available.",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SSN last 4 must be exactly 4 digits.", regex="^\\d{4}$"
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[0-9()+.\\-\\s]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[0-9()+.\\-\\s]{7,20}$",
                            )
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy",
                        to="shared.address",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacies",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pharmacies",
                "ordering": ["name"],
                "unique_together": {("facility", "name")},
            },
        ),
        migrations.CreateModel(
            name="CareProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("organization_name", models.CharField(blank=True, max_length=150)),
                ("specialty", models.CharField(blank=True, max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[0-9()+.\\-\\s]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[0-9()+.\\-\\s]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "npi",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NPI must be 10 digits.", regex="^\\d{10}$"
                            )
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="care_provider",
                        to="shared.address",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_providers",
                        to="facilities.facility",
                    ),
                ),
                (
                    "linked_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_profiles",
                        to="facilities.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "organization_name"],
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="pcp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_care_patients",
                to="patients.careprovider",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_pharmacy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="patients.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="referring_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_patients",
                to="patients.careprovider",
            ),
        ),
    ]
