# Generated by Django 4.2.29 on 2026-04-22 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_email_patient_middle_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.",
                        regex="^[0-9()+.\\-\\s]{7,20}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
