# Generated by Codex on 2026-04-24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pharmacy",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="source",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("imported", "Imported"),
                    ("directory", "Directory"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
