# Generated by Codex on 2026-04-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organizationpharmacypreference"),
        ("patients", "0004_pharmacy_global_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pharmacy",
            name="facility",
        ),
    ]
