# Generated by Codex on 2026-04-24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_patient_default_pharmacies(apps, _schema_editor):
    Patient = apps.get_model("patients", "Patient")
    PatientPharmacy = apps.get_model("patients", "PatientPharmacy")

    for patient in Patient.objects.exclude(preferred_pharmacy_id__isnull=True):
        PatientPharmacy.objects.get_or_create(
            patient_id=patient.id,
            pharmacy_id=patient.preferred_pharmacy_id,
            defaults={
                "is_default": True,
                "is_active": True,
            },
        )


def noop_reverse(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_remove_pharmacy_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="accepts_erx",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="dea_number",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="DEA number must use 2 letters followed by 7 digits.",
                        regex="^[A-Za-z]{2}\\d{7}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="directory_source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="directory_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_24_hour",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="last_directory_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="legal_business_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="ncpdp_id",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="NCPDP ID must be 7 digits.",
                        regex="^\\d{7}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="npi",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="NPI must be 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("mail_order", "Mail Order"),
                    ("specialty", "Specialty"),
                    ("ltc", "Long-Term Care"),
                    ("dme", "DME"),
                    ("home_infusion", "Home Infusion"),
                    ("other", "Other"),
                ],
                default="retail",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="store_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="tax_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="PatientPharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_preferences",
                        to="patients.patient",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_preferences",
                        to="patients.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "pharmacy__name"],
                "unique_together": {("patient", "pharmacy")},
            },
        ),
        migrations.AddConstraint(
            model_name="patientpharmacy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True)),
                fields=("patient",),
                name="unique_active_default_patient_pharmacy",
            ),
        ),
        migrations.RunPython(backfill_patient_default_pharmacies, noop_reverse),
    ]
