# Generated by Django 4.2.29 on 2026-04-24 03:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_emergency_contacts(apps, schema_editor):
    Patient = apps.get_model("patients", "Patient")
    PatientEmergencyContact = apps.get_model("patients", "PatientEmergencyContact")

    for patient in Patient.objects.exclude(emergency_contact_name=""):
        PatientEmergencyContact.objects.create(
            patient_id=patient.id,
            name=patient.emergency_contact_name,
            relationship=patient.emergency_contact_relationship,
            phone_number=patient.emergency_contact_phone,
            is_primary=True,
        )


def clear_backfilled_emergency_contacts(apps, schema_editor):
    PatientEmergencyContact = apps.get_model("patients", "PatientEmergencyContact")
    PatientEmergencyContact.objects.filter(is_primary=True, notes="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_pharmacy_erx_fields_patientpharmacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientEmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[0-9()+.\\-\\s]{7,20}$",
                            )
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.RunPython(
            backfill_emergency_contacts,
            clear_backfilled_emergency_contacts,
        ),
        migrations.AddConstraint(
            model_name="patientemergencycontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("patient",),
                name="unique_primary_emergency_contact",
            ),
        ),
    ]
