# Generated by Codex on 2026-04-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_patientemergencycontact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ssn",
            field=models.CharField(
                blank=True,
                help_text="Full SSN. Display masked by default in the application.",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SSN must be exactly 9 digits.",
                        regex="^\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ssn_last4",
            field=models.CharField(
                blank=True,
                help_text="Derived from SSN when available; retained for legacy display.",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SSN last 4 must be exactly 4 digits.",
                        regex="^\\d{4}$",
                    )
                ],
            ),
        ),
    ]
