# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_patient_ssn"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hispanic_or_latino", "Hispanic or Latino"),
                    ("not_hispanic_or_latino", "Not Hispanic or Latino"),
                    ("unknown", "Unknown"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="ethnicity_declined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_language_declined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "american_indian_or_alaska_native",
                        "American Indian or Alaska Native",
                    ),
                    ("asian", "Asian"),
                    ("black_or_african_american", "Black or African American"),
                    (
                        "native_hawaiian_or_other_pacific_islander",
                        "Native Hawaiian or Other Pacific Islander",
                    ),
                    ("white", "White"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="race_declined",
            field=models.BooleanField(default=False),
        ),
    ]
