# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_patient_demographic_standards"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lab", "Lab Reports"),
                            ("imaging", "Radiology & Imaging"),
                            ("referrals", "Referrals & Consults"),
                            ("admin", "Administrative"),
                            ("consent", "Consent Forms"),
                        ],
                        default="admin",
                        max_length=30,
                    ),
                ),
                ("document_date", models.DateField(blank=True, null=True)),
                ("uploaded_by_name", models.CharField(blank=True, max_length=150)),
                ("file_size_display", models.CharField(blank=True, max_length=40)),
                ("file_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_documents",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-document_date", "-created_at", "name"],
            },
        ),
    ]
