# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_patientdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdocument",
            name="content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="file_size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patientdocument",
            field=models.CharField(blank=True, max_length=500),
            name="storage_key",
        ),
    ]
