# Generated by Django 4.2.29 on 2026-04-26 19:40

from django.db import migrations, models

import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0011_patientdocument_storage_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careprovider",
            name="fax_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[patients.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="careprovider",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[patients.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[patients.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="patientemergencycontact",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[patients.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="patientphone",
            name="number",
            field=models.CharField(
                max_length=20, validators=[patients.models.validate_phone_number]
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="fax_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[patients.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[patients.models.validate_phone_number],
            ),
        ),
    ]
