# Generated by Codex on 2026-04-26

import django.core.validators
from django.db import migrations, models
from django.db.models import Q

CHART_NUMBER_START = 100
CHART_NUMBER_STEP = 10


def normalize_chart_numbers(apps, schema_editor):
    Patient = apps.get_model("patients", "Patient")

    facility_ids = (
        Patient.objects.exclude(facility_id__isnull=True)
        .order_by("facility_id")
        .values_list("facility_id", flat=True)
        .distinct()
    )

    for facility_id in facility_ids:
        patients = Patient.objects.filter(facility_id=facility_id).order_by(
            "created_at",
            "id",
        )
        for index, patient in enumerate(patients):
            Patient.objects.filter(pk=patient.pk).update(
                chart_number=str(CHART_NUMBER_START + index * CHART_NUMBER_STEP)
            )


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0012_alter_careprovider_fax_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="chart_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="MRN must contain digits only.",
                        regex="^\\d+$",
                    )
                ],
            ),
        ),
        migrations.RunPython(normalize_chart_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=~Q(chart_number__isnull=True) & ~Q(chart_number=""),
                fields=("facility", "chart_number"),
                name="unique_patient_chart_number_per_facility",
            ),
        ),
    ]
