# Generated by Codex on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models

DEFAULT_DOCUMENT_CATEGORIES = [
    {"code": "lab", "name": "Lab Reports", "sort_order": 10},
    {"code": "imaging", "name": "Radiology & Imaging", "sort_order": 20},
    {"code": "referrals", "name": "Referrals & Consults", "sort_order": 30},
    {"code": "admin", "name": "Administrative", "sort_order": 40},
    {"code": "consent", "name": "Consent Forms", "sort_order": 50},
]


def seed_document_categories(apps, schema_editor):
    Facility = apps.get_model("facilities", "Facility")
    PatientDocumentCategory = apps.get_model("patients", "PatientDocumentCategory")

    for facility in Facility.objects.all():
        for category in DEFAULT_DOCUMENT_CATEGORIES:
            PatientDocumentCategory.objects.get_or_create(
                facility=facility,
                code=category["code"],
                defaults={
                    "name": category["name"],
                    "sort_order": category["sort_order"],
                    "is_active": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0011_document_category_permission"),
        ("patients", "0013_numeric_chart_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=30)),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_categories",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient document categories",
                "ordering": ["sort_order", "name"],
                "unique_together": {("facility", "code")},
            },
        ),
        migrations.AlterField(
            model_name="patientdocument",
            name="category",
            field=models.CharField(default="admin", max_length=30),
        ),
        migrations.RunPython(seed_document_categories, migrations.RunPython.noop),
    ]
