# Generated by Codex on 2026-04-26

from django.db import migrations, models

DEFAULT_DOCUMENT_CATEGORIES = [
    {"code": "clinical", "name": "Clinical Notes", "sort_order": 10},
    {"code": "lab", "name": "Lab Reports", "sort_order": 20, "is_system": True},
    {
        "code": "imaging",
        "name": "Radiology & Imaging",
        "sort_order": 30,
        "is_system": True,
    },
    {"code": "referrals", "name": "Referrals & Consults", "sort_order": 40},
    {"code": "insurance", "name": "Insurance & Benefits", "sort_order": 50},
    {"code": "admin", "name": "Administrative", "sort_order": 60, "is_system": True},
    {"code": "consent", "name": "Consent Forms", "sort_order": 70, "is_system": True},
]


def seed_document_categories(apps, schema_editor):
    Facility = apps.get_model("facilities", "Facility")
    PatientDocumentCategory = apps.get_model("patients", "PatientDocumentCategory")

    for facility in Facility.objects.all():
        for category in DEFAULT_DOCUMENT_CATEGORIES:
            defaults = {
                "name": category["name"],
                "sort_order": category["sort_order"],
                "is_system": category.get("is_system", False),
                "is_active": True,
            }
            document_category, created = PatientDocumentCategory.objects.get_or_create(
                facility=facility,
                code=category["code"],
                defaults=defaults,
            )
            if created:
                continue

            updates = set()
            if category.get("is_system", False) and not document_category.is_system:
                document_category.is_system = True
                updates.add("is_system")
            if document_category.sort_order != category["sort_order"]:
                document_category.sort_order = category["sort_order"]
                updates.add("sort_order")
            if updates:
                document_category.save(update_fields=sorted(updates))


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0014_document_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdocumentcategory",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            seed_document_categories,
            migrations.RunPython.noop,
        ),
    ]
