# Generated by Django 4.2.29 on 2026-04-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(
                choices=[("US", "United States")], default="US", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                choices=[
                    ("NY", "New York"),
                    ("CA", "California"),
                    ("TX", "Texas"),
                    ("FL", "Florida"),
                ],
                max_length=2,
            ),
        ),
    ]
