# Generated by Django 4.2.29 on 2026-04-21 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_address_country_alter_address_city_and_more"),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization",
                to="shared.address",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
