# Generated by Codex on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


def create_preferences_for_existing_facility_pharmacies(apps, _schema_editor):
    Pharmacy = apps.get_model("patients", "Pharmacy")
    OrganizationPharmacyPreference = apps.get_model(
        "organizations",
        "OrganizationPharmacyPreference",
    )

    for pharmacy in Pharmacy.objects.select_related("facility").all():
        facility = getattr(pharmacy, "facility", None)
        if not facility or not facility.organization_id:
            continue

        OrganizationPharmacyPreference.objects.get_or_create(
            organization_id=facility.organization_id,
            pharmacy_id=pharmacy.id,
            defaults={
                "is_preferred": True,
                "is_hidden": False,
                "is_active": pharmacy.is_active,
            },
        )


def noop_reverse(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_pharmacy_global_fields"),
        ("organizations", "0003_organization_address_organization_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationPharmacyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_preferred", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_preferences",
                        to="organizations.organization",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_preferences",
                        to="patients.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pharmacy__name"],
                "unique_together": {("organization", "pharmacy")},
            },
        ),
        migrations.RunPython(
            create_preferences_for_existing_facility_pharmacies,
            noop_reverse,
        ),
    ]
