# Generated by Django 4.2.29 on 2026-04-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="room",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="appointment",
            name="visit_mode",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("telehealth", "Telehealth"),
                    ("phone", "Phone"),
                    ("home", "Home"),
                ],
                default="office",
                max_length=20,
            ),
        ),
    ]
