# Generated by Django 4.2.29 on 2026-04-24 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0006_facilityresource"),
        ("appointments", "0005_rename_internal_notes_remove_patient_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="facilities.facilityresource",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
