# Generated by Codex on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0009_remove_appointment_doctor_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="visit_mode",
        ),
    ]
