# Generated by Django 4.2.29 on 2026-04-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stafftitle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
