# Generated by Django 4.2.29 on 2026-04-19 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shared", "0002_address_country_alter_address_city_and_more"),
        ("facilities", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientgender",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_genders",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facility",
                to="shared.address",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilities",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="appointmenttype",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_types",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="appointmentstatus",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_statuses",
                to="facilities.facility",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stafftitle",
            unique_together={("facility", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="staffrole",
            unique_together={("facility", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together={("user", "facility")},
        ),
        migrations.AlterUniqueTogether(
            name="patientgender",
            unique_together={("facility", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="appointmenttype",
            unique_together={("facility", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="appointmentstatus",
            unique_together={("facility", "code")},
        ),
    ]
