# Generated by Django 4.2.29 on 2026-04-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmentstatus",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="appointmentstatus",
            name="is_deletable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appointmenttype",
            name="is_deletable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patientgender",
            name="is_deletable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffrole",
            name="is_deletable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stafftitle",
            name="is_deletable",
            field=models.BooleanField(default=True),
        ),
    ]
