# Generated by Django 4.2.29 on 2026-04-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_alter_appointmentstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"ordering": ["name"], "verbose_name_plural": "Facilities"},
        ),
        migrations.AddField(
            model_name="facility",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
