# Generated by Django 4.2.29 on 2026-04-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0004_alter_facility_options_facility_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="facility",
            name="fax_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="facility",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
