# Generated by Django 4.2.29 on 2026-04-24 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0005_facility_email_facility_facility_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deletable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="facilities.facility",
                    ),
                ),
                (
                    "linked_staff",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource",
                        to="facilities.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
    ]
