# Generated by Codex on 2026-04-25

from django.db import migrations, models

from facilities.security import (
    get_role_security_template,
    normalize_security_permissions,
)


def seed_role_security_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")

    for role in StaffRole.objects.all():
        current_permissions = role.security_permissions or {}
        template = get_role_security_template(role.code)

        if current_permissions:
            role.security_permissions = normalize_security_permissions(
                current_permissions
            )
        else:
            role.security_permissions = template

        role.save(update_fields=["security_permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0006_facilityresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffrole",
            name="security_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="staff",
            name="security_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            seed_role_security_permissions,
            migrations.RunPython.noop,
        ),
    ]
