# Generated by Codex on 2026-04-26

import datetime

from django.db import migrations, models

import facilities.models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0007_staff_security_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="operating_start_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name="facility",
            name="operating_end_time",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name="facility",
            name="operating_days",
            field=models.JSONField(
                blank=True, default=facilities.models.default_operating_days
            ),
        ),
    ]
