# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0008_facility_operating_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityresource",
            name="default_room",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="facilityresource",
            name="operating_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facilityresource",
            name="operating_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
