# Generated by Codex on 2026-04-26

import colorfield.fields
from django.db import migrations

STATUS_COLORS = {
    "pending": "#fbbf24",
    "check_in": "#60a5fa",
    "check_out": "#34d399",
    "cancelled": "#fb7185",
    "no_show": "#94a3b8",
}

TYPE_COLORS = {
    "new_patient": "#818cf8",
    "follow_up": "#93c5fd",
    "annual": "#86efac",
    "consult": "#7dd3fc",
    "procedure": "#c084fc",
    "urgent": "#fda4af",
}


def soften_default_colors(apps, schema_editor):
    AppointmentStatus = apps.get_model("facilities", "AppointmentStatus")
    AppointmentType = apps.get_model("facilities", "AppointmentType")

    for code, color in STATUS_COLORS.items():
        AppointmentStatus.objects.filter(code=code, is_deletable=False).update(
            color=color
        )

    for code, color in TYPE_COLORS.items():
        AppointmentType.objects.filter(code=code, is_deletable=False).update(
            color=color
        )


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0009_facilityresource_room_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentstatus",
            name="color",
            field=colorfield.fields.ColorField(
                default="#94a3b8", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="appointmenttype",
            name="color",
            field=colorfield.fields.ColorField(
                default="#c084fc", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.RunPython(soften_default_colors, migrations.RunPython.noop),
    ]
