# Generated by Codex on 2026-04-26

from django.db import migrations

PERMISSION_KEY = "documents.categories.manage"


def add_document_category_permission(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")

    for role in StaffRole.objects.all():
        permissions = dict(role.security_permissions or {})
        permissions[PERMISSION_KEY] = role.code == "admin"
        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0010_soften_default_appointment_colors"),
    ]

    operations = [
        migrations.RunPython(
            add_document_category_permission,
            migrations.RunPython.noop,
        ),
    ]
