# Generated by Codex on 2026-04-24

from django.db import migrations, models


def backfill_coverage_order(apps, schema_editor):
    PatientInsurancePolicy = apps.get_model("insurance", "PatientInsurancePolicy")
    PatientInsurancePolicy.objects.filter(is_primary=True).update(
        coverage_order="primary"
    )
    PatientInsurancePolicy.objects.filter(is_primary=False).update(
        coverage_order="secondary"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinsurancepolicy",
            name="coverage_order",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("other", "Other"),
                ],
                default="secondary",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_coverage_order, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="patientinsurancepolicy",
            options={
                "ordering": [
                    "patient",
                    "-is_primary",
                    "coverage_order",
                    "carrier__name",
                ],
            },
        ),
    ]
